### PR TITLE
FACES-3142 Create LSV-169 portlet and tester

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
backported <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ngriffin7a** [comment]
please run magic script for liferay-faces-portlet.git branches and send follow-up PRs <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ngriffin7a** [comment]
Merged, thank you. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by stiemannkj1** [comment]
@ngriffin7a, that shouldn't be necessary. Only the TCK test pages in **`pluto-portal-driver-config.xml`** are extracted and created by the `test-setup-hook` in Liferay (though perhaps other test pages should function the same, they don't currently though). This change should be sufficient: https://github.com/liferay/liferay-faces-portal/pull/188

**Pull request closed without merging**
