### PR TITLE
FACES-3251 Move portal-issues-portlet testers into jsf-issues-portlet in bridge-impl repo

### PR DESCRIPTION
**Pull request by stiemannkj1**
Merging. Please review this code if/when you have time, @ngriffin7a.
You may also want to take a look at the commit where I removed this portlet from the portal repo: https://github.com/liferay/liferay-faces-portal/commit/d0c173fb289b8a982f84918777947c69e085fe27

### CODE REVIEW

**Comment by ngriffin7a** [comment]
@stiemannkj1 Why was the liferay-faces-portal dependency necessary in the tests that were removed from https://github.com/liferay/liferay-faces-portal/commit/d0c173fb289b8a982f84918777947c69e085fe27 but the dependency is not necessary here in liferay-faces-bnridge-impl? BTW, it is a good thing that it is not necessary, otherwise we would introduce circular Git repo dependencies which we have avoided thus far.

**Comment by stiemannkj1** [comment]
@ngriffin7a, looks like the Portal repo was just there for no reason. I don't think the test was depending on it in any way.

**Comment by stiemannkj1** [comment]
@ngriffin7a, meant dependency **not** repo, sorry.

**Comment by ngriffin7a** [comment]
@stiemannkj1 OK hopefully future issue tests will not require the liferay-faces-portal dependency. If any future ones do, then we should bring back the portal-issues-portlet in the liferay-faces-portal.git repo.

**Comment by stiemannkj1** [comment]
@ngriffin7a, agreed, but we should make sure to keep the portal-issues-war only for issues with the Portal jar. Issues with bridge-ext (like FACES-257) should be tested in the jsf-issues-portlet in bridge-impl. Also, I would guess that we'll be able to test most issues with the Portal jar by just beefing up the showcase. Hopefully that makes it clearer why I moved the tests (also eliminating another war is always a good thing).

**Pull request merged**
