### PR TITLE
Revert 38f91b64: FACES-2945 The ResourceImpl.toRequestPath() method should not encode the return value (replace with alternative solution)

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Comment by stiemannkj1** [comment]
@ngriffin7a, please backport to `5.x`.

**Comment by stiemannkj1** [comment]
Improvements TODO:

- [ ] Use `FacesContext` attribute to disable encoding for PrimeFaces (constant in `BridgeExt`) instead of `ApplicationPrimeFacesHeadImpl`
- [ ] Move `RES_NOT_FOUND` into `BridgeExt`
- [ ] Rename `ResourceInnerImpl` and `ResourceOuterImpl` to make purpose clearer
- [ ] Rename `ResourceHandlerRichfacesImpl` to `ResourceHandlerRichFacesImpl`
- [ ] Attempt to use `inner.faces-config.xml`, `outer.faces-config.xml`, and `richfaces.faces-config.xml`
- [ ] ~~Consider something like a `PortletURLInspector` instead `PortletResourceUtilCompat`.~~ After consideration, I think I have a much better idea. We can create an interface in the Bridge Impl:

    ```
    public interface PortletResoruceURLHandler {
        public boolean isResourceURL(String url);
    }
    ```

    `ResourceHandlerOuterImpl` can implement this interface and `PortletResourceUtilCompat.isPortletResourceURL()`'s functionality can be moved to `ResourceHandlerOuterImpl.isResourceURL()`.  In `BridgeURLResourceImpl` to check if a URL is a portlet resource url, we should get the `ResourceHandler` chain, cast it to `PortletResoruceURLHandler`, and call `isResourceURL()` (this will eliminate diffs in backports). In JSF 2.1 and below, the developer would be unable to override `isResourceURL()` because it is defined in a private bridge impl interface. However, in JSF 2.2 and above `ResourceHandler` also implements `isResourceURL()`, so `ResourceHandlerOuterImpl.isResourceURL()` should consult the delegation chain first, then use the Bridge's version (`ResourceHandlerOuterImpl.isResourceURL()` should return `false` so we never consult Mojarra's servlet based `ResourceHandler`). Then any `ResourceHandler`'s which we wrap will have an opportunity to declare that a URL is a resource URL.

    This solution will not help people who want to implement a bridge for JSF 2.1 and below, but we don't need to worry about that since the latest bridge spec is for JSF 2.2 anyway.

**Comment by ngriffin7a** [comment]
Merged. Thank you.

**Comment by ngriffin7a** [comment]
Merged and backported to 5.x. Thank you.

**Pull request merged**
