### PR TITLE
Workaround FACES-2677 Primefaces state list items appear after SPA navigation to and from primefaces-applicant-portlet on Liferay 7.0

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
Merged into master (6.x) and backported to 5.x and 4.x. Thank you.

**Comment by stiemannkj1** [comment]
@ngriffin7a, this fix won't work for `4.x` (JSF 2.1), but I think it's good to have there so we can come up with an alternative workaround if we need to.

**Comment by ngriffin7a** [comment]
@stiemannkj1 Could we simply remove `xmlns:p="http://xmlns.jcp.org/jsf/passthrough"` so that at least it renders for Liferay 6.2 + JSF 2.1? Right now it might not render because of that.

**Comment by ngriffin7a** [comment]
@stiemannkj1 On second thought, the `4.x` branch is for JSF 2.2 -- so all should be well right?

**Comment by stiemannkj1** [comment]
@ngriffin7a, yeah, I was mixed up with bridge-ext, 4.x is JSF 2.2 so everything is fine.

**Pull request merged**
