### PR TITLE
FACES-3211 PhantomJS ghostdriver dependency is not test scoped

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
bp 5.x 4.x 3.x but please review 2.x backport commit https://github.com/liferay/liferay-faces-bridge-impl/commit/1ca7b168962ef63115df2158a479205a64a6d3c2 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ngriffin7a** [comment]
Merged, thank you. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by stiemannkj1** [comment]
@ngriffin7a, backport looks good to me. Ran the tests on `2.x` and they worked.

**Comment by ngriffin7a** [comment]
@stiemannkj1 thanks.

**Pull request closed without merging**
