### PR TITLE
change-RequestScoped-to-BridgeRequestScoped-with-Extension

### PR DESCRIPTION
**Pull request by stiemannkj1**
@ngriffin7a, here's my idea for replacing `@RequestScoped` with `@BridgeRequestScoped`. I'm just putting this here for posterity while it's fresh in my mind. I'll return to this in the new year. The code is untested and won't compile, but it should be trivial to make it compile (just missing imports, formatting).

### CODE REVIEW

**Comment by stiemannkj1** [comment]
Related:
- https://github.com/liferay/liferay-portal/blob/master/modules/apps/bean-portlet/bean-portlet-cdi-extension/src/main/java/com/liferay/bean/portlet/cdi/extension/internal/BeanPortletExtension.java
- https://github.com/stiemannkj1/liferay-faces-bridge-impl/blob/thin-wab-OSGi-WIP-4.x/bridge-impl/src/main/java/com/liferay/faces/bridge/servlet/BridgeExtension.java

**Comment by ngriffin7a** [comment]
@stiemannkj1 Apologies for taking so long to get back to you. I had to focus on the JSF thin WAR release and associated archetypes first.

I just spent the day trying to incorporate your idea into the latest version of BridgePortableExtension.java which is now [BridgeExtension.java](https://github.com/liferay/liferay-faces-bridge-impl/blob/master/bridge-impl/src/main/java/com/liferay/faces/bridge/servlet/BridgeExtension.java)

Sadly, with CDI, it is not possible to use more than one `@Observes` annotation like you specified:
```
private <T> void step3ProcessAnnotatedType(
 	@Observes ProcessAnnotatedType<T> processAnnotatedType,
 	@Observes ServletContext servletContext) {
 	...
}
```

But even if it were possible, it still wouldn't work because the CDI context associated with `@ApplicationScoped` (basically, a fully initialized `ServletContext`) simply isn't ready when processing annotated types. Here is an example from a Liferay Portal CDI extension that observes it, and it is much later in the lifecycle of the extension:
https://github.com/liferay/liferay-portal/blob/11e6081f96abb6bf299369519434c1eafa0658e3/modules/apps/bean-portlet/bean-portlet-cdi-extension/src/main/java/com/liferay/bean/portlet/cdi/extension/internal/CDIBeanPortletExtension.java#L430

So even though I am inclined to have an opt-in/opt-out type of feature for making `@RequestScoped` automatically convert to `@BridgeRequestScoped`, I can't see a way to let the developer specify an opt-in.

If you have any ideas, please let me know. Otherwise I'm going to move on for now and try to finish JSR 378 and get it submitted. Thanks.

**Comment by ngriffin7a** [comment]
@stiemannkj1 I just tried the following with Pluto:

```
	private <T> void step2ProcessAnnotatedType(@Observes ProcessAnnotatedType<T> processAnnotatedType, BeanManager beanManager) {
		...
		Set<Bean<?>> beanSet = beanManager.getBeans("servletContext");
		...
	}
```

And it doesn't work there either. Weld reported that it wasn't possible to call `BeanManager.getBeans(String)` during application initialization.

Thanks so much for the idea and for taking the time to create a pull request. But at this point I'll be closing it. Let me know if you want to reopen it or present a different approach in the future.

**Comment by stiemannkj1** [comment]
Thanks for taking a look,  @ngriffin7a! If the only issue with this solution is the `ServletContext`, what if we extract the `@RequestScoped` -> `@BridgeRequestScoped` feature of the CDI portable extension into its own API class? Then if folks want to auto convert to `@BridgeRequestScoped` they just add the class name to their existing `META-INF/services/javax.enterprise.inject.spi.Extension` file and it'll convert the scopes. It's configurable at the application level which is nice. Maybe even have it by default in the demos and archetypes? What do you think?

**Comment by stiemannkj1** [comment]
So if you want to convert the scopes, you add the extension to `META-INF/services/javax.enterprise.inject.spi.Extension`:

```
com.liferay.faces.bridge.cdi.internal.BridgePortableExtension
com.liferay.faces.bridge.cdi.ConvertRequestScopedToBridgeRequestScoped
```

If not, you don't include the extension:

```
com.liferay.faces.bridge.cdi.internal.BridgePortableExtension
```

**Comment by ngriffin7a** [comment]
@stiemannkj1 Done!

See:
https://github.com/liferay/liferay-faces-bridge-api/commit/72b438d352823340eeedd7bc9cb0644eb126d892

And:
https://github.com/liferay/liferay-faces-bridge-impl/commit/f6e05a9e6a704f2867cc10aa566421009755d79f

**Comment by stiemannkj1** [comment]
Fantastic! Thanks so much @ngriffin7a!

**Comment by ngriffin7a** [comment]
@stiemannkj1 TCK tests! https://github.com/liferay/liferay-faces-bridge-impl/commit/d6c1bc5a60506d97466cca0eecebb03ef9ab6127

**Comment by stiemannkj1** [comment]
@ngriffin7a, oh wow, that's great! So cool to see this make it in to the spec and TCK!

**Pull request closed without merging**
