### PR TITLE
FACES-2584 Some of the demo portlets are missing the javax.faces.PROJ…

### PR DESCRIPTION
**Pull request by pcwhite**
…ECT_STAGE web.xml context-param

### CODE REVIEW

**Comment by pcwhite** [comment]
can be forward-ported to master, and back-ported to 3.x (not 2.x)

**Comment by stiemannkj1** [comment]
@pcwhite, did you check that the issues portlets are consistent as well?

Also, you may want to do the backports and forwardports yourself since there may be a different number of demos in each branch.

**Comment by pcwhite** [comment]
@stiemannkj1 thanks for checking!  I still need to add comments to the issues portlets, and i'll do the ports myself too.

**Comment by ngriffin7a** [comment]
Merged into 4.x, forward-ported to master (5.x) and backported to 3.x. Thank you.

**Pull request merged**
